name: Pipeline DevOps SENA
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prueba-y-validacion:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose-plugin

      - name: Validar configuración de Docker Compose
        run: docker compose config

      - name: Construir imágenes
        run: docker compose build --no-cache

      - name: Levantar los servicios
        run: docker compose up -d

      - name: Esperar que arranquen
        run: sleep 15

      - name: Probar que el backend responda
        run: curl --fail http://localhost:5000/api/mensaje

      - name: Probar que el frontend cargue
        run: curl --fail http://localhost:8080

      - name: Limpiar contenedores
        run: docker compose down